server:
  port: 8868

spring:
  application:
    name: cloud-cosuumer-common
  zipkin:
    base-url: http://192.168.0.88:9411
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
  redis:
    host: 192.168.0.88
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 50
        #连接池中的最小空闲连接
        min-idle: 0
    #连接超时时间（毫秒）
    timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持

ribbon:
  #设置调用超时时间
  ReadTimeout:  5000
  ConnectTimeout: 5000


serveraddress: http://39.97.187.244



