server:
  port: 2233

spring:
  application:
    name: cloud-file_operation
  servlet:
    multipart:
      max-file-size: 100MB  #单个文件上传大小
      max-request-size: 100MB  #总共上传大小
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://121.30.208.197:3306/hy?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: huayan
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis:
  type-aliases-package: com.web.pojo