server:
  port: 8001

spring:
  application:
    name: cloud-provider-web
  zipkin:
    base-url: http://192.168.0.88:9411
    sleuth:
      sampler:
        probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.0.88:3306/txmountainspring?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.web.pojo